# Generated by Django 5.0.3 on 2024-05-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="token"),
        ),
    ]
