# Generated by Django 5.0.6 on 2024-05-23 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("change_active", "Can change is_active")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
