# Generated by Django 5.0.3 on 2024-04-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
                ("last_used", models.DateField(auto_now=True, verbose_name="Дата последнего использования")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Название рассылки")),
                ("first_use", models.DateTimeField(auto_now=True, verbose_name="Дата и время первого использования")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("DAY", "раз в день"), ("WEEK", "раз в неделю"), ("MONTH", "раз в месяц")],
                        default="MONTH",
                        max_length=8,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CR", "Создана"), ("LA", "Запущена"), ("CP", "Завершена"), ("PA", "Пауза")],
                        default="CR",
                        max_length=2,
                        verbose_name="Статус",
                    ),
                ),
                ("clients", models.ManyToManyField(to="data_statistics.client", verbose_name="Клиенты рассылки")),
                (
                    "statistics",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_statistics.mailingstat",
                        verbose_name="Статистика",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
