# Generated by Django 5.0.3 on 2024-04-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Название рассылки")),
                ("datetime_start", models.DateTimeField(verbose_name="Дата и время старта")),
                ("datetime_stop", models.DateTimeField(verbose_name="Дата и время окончания")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("DAY", "раз в день"), ("WEEK", "раз в неделю"), ("MONTH", "раз в месяц")],
                        default="MONTH",
                        max_length=8,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CR", "Создана"), ("LA", "Запущена"), ("CP", "Завершена"), ("PA", "Пауза")],
                        default="CR",
                        max_length=2,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
                ("last_used", models.DateField(auto_now=True, verbose_name="Дата последнего использования")),
                (
                    "mailing",
                    models.OneToOneField(
                        blank=True,
                        default=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mailing.mailing",
                        verbose_name="Активная рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
