# Generated by Django 5.0.3 on 2024-05-11 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="datetime_start",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="datetime_stop",
        ),
        migrations.AddField(
            model_name="mailing",
            name="time_start",
            field=models.TimeField(
                default=datetime.datetime(2024, 5, 11, 15, 14, 5, 357249, tzinfo=datetime.timezone.utc),
                verbose_name="Дата и время старта",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="time_stop",
            field=models.TimeField(
                default=datetime.datetime(2024, 5, 11, 15, 14, 5, 357295, tzinfo=datetime.timezone.utc),
                verbose_name="Дата и время окончания",
            ),
        ),
    ]
