# Generated by Django 5.0.3 on 2024-05-11 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_remove_mailing_datetime_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="time_start",
            field=models.TimeField(default=django.utils.timezone.now, verbose_name="Дата и время старта"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="time_stop",
            field=models.TimeField(default=django.utils.timezone.now, verbose_name="Дата и время окончания"),
        ),
    ]
