# Generated by Django 5.0.3 on 2024-04-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_alter_mailing_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[("DAY", "раз в день"), ("WEEK", "раз в неделю"), ("MONTH", "раз в месяц")],
                default="MONTH",
                max_length=8,
                verbose_name="Периодичность",
            ),
        ),
    ]
