# Generated by Django 5.0.6 on 2024-05-19 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_alter_mailing_time_start_alter_mailing_time_stop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="time_start",
            field=models.TimeField(default=django.utils.timezone.now, verbose_name="Время старта"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="time_stop",
            field=models.TimeField(default=django.utils.timezone.now, verbose_name="Время окончания"),
        ),
    ]
