# Generated by Django 5.0.6 on 2024-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0004_alter_mailing_time_start_alter_mailing_time_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активная рассылка"),
        ),
    ]
