# Generated by Django 5.0.6 on 2024-05-23 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0006_mailing_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("change_active", "Can change is_active")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
