# Generated by Django 5.0.6 on 2024-05-24 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0007_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("change_active", "Can change is_active"),
                    ("detail_mailing", "Can Detail view mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
