# Generated by Django 5.0.3 on 2024-04-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Имя")),
                ("surname", models.CharField(max_length=64, verbose_name="Фамилия")),
                ("email", models.EmailField(max_length=64, unique=True, verbose_name="Адрес электронной почты")),
                ("comment", models.CharField(blank=True, max_length=128, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="MailingStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="Название статистики рассылки")),
                ("attempt_datetime", models.DateTimeField(verbose_name="Дата и время последней попытки")),
                ("status_attempt", models.BooleanField(default=False, verbose_name="Статус попытки")),
                ("response", models.CharField(max_length=128, verbose_name="Ответ почтового сервера")),
            ],
            options={
                "verbose_name": "Статистика Email рассылки",
                "verbose_name_plural": "Статистики Email рассылки",
            },
        ),
    ]
