# Generated by Django 5.0.3 on 2024-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_statistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingstat",
            name="attempt_datetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время последней попытки"),
        ),
    ]
