# Generated by Django 5.0.6 on 2024-05-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Содержимое")),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/", verbose_name="Превью")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("views_count", models.IntegerField(default=0, verbose_name="Просмотры")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
